services:
  carta:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carta-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      CARTA_HOST: "0.0.0.0"
      CARTA_PORT: "8443"
      CARTA_USE_TLS: "0"
      SQLITE_URL: "sqlite+aiosqlite:///./data/carta.db"
      TZ: Europe/Moscow
    volumes:
      - carta_data:/app/data
    ports:
      - "127.0.0.1:8443:8443"

volumes:
  carta_data:
